/*---------------------------------------------------------------------
 *
 * Program: AS_ECHO.EXE  Asynch Echo Server (TCP)
 *
 * filename: as_echo.h
 *
 * copyright by Bob Quinn, 1995
 *   
 *  Description:
 *    Used by as_echo.rc
 ---------------------------------------------------------------------*/
#include <winsock.h>
#include "..\winsockx.h"
#include <ver.h>

#ifndef IDC_STATIC
#define IDC_STATIC -1
#endif
