//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by WSASIMPL.RC
//
#define CHARGEN_SEQ                     19
#define SIMPLTST                        101
#define IDM_EXIT                        102
#define IDD_HOST                        102
#define IDM_CONNECT                     103
#define IDM_START                       104
#define IDD_ABOUT                       104
#define IDM_CLOSE                       105
#define IDD_DIALOG1                     105
#define IDM_ABOUT                       106
#define IDC_HOST                        1029
#define IDC_COMPILEDATE                 1050
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        108
#define _APS_NEXT_COMMAND_VALUE         107
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
