//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by UA_TIME.RC
//
#define ID_UA_TIME                      3
#define CHARGEN_SEQ                     19
#define IDI_UA_TIME                     120
#define UA_TIME                         120
#define IDM_OPEN                        121
#define IDM_START_STOP                  123
#define IDM_BIND                        130
#define IDM_SENDTO                      132
#define IDM_SEND                        133
#define IDM_ASYNC                       134
#define ID_SENDTO                       135
#define IDM_EXIT                        1006
#define IDM_WRITE_READ                  1007
#define IDM_WRITE                       1008
#define IDM_READ_WRITE                  1009
#define IDM_READ                        1010
#define IDC_COMPILEDATE                 1050
#define IDC_ACCEPTCONN                  1051
#define IDC_BROADCAST                   1053
#define IDC_DEBUG                       1054
#define IDC_DONTLINGER                  1055
#define IDS_DLLVER                      1055
#define IDC_DONTROUTE                   1056
#define IDS_DLLHIVER                    1056
#define IDC_ERROR                       1057
#define IDC_KEEPALIVE                   1058
#define IDC_LINGER                      1059
#define IDS_MAXSOCKS                    1059
#define IDC_OOBINLINE                   1060
#define IDS_MAXUDP                      1060
#define IDC_RCVBUF                      1061
#define IDC_REUSEADDR                   1062
#define IDC_SNDBUF                      1063
#define IDC_TYPE                        1064
#define IDC_TCPNODELAY                  1065
#define IDS_DESCRIP                     1065
#define IDC_SOCKIN                      1066
#define IDS_STATUS                      1066
#define IDC_LEVELIN                     1067
#define IDC_OPTVAL                      1068
#define IDC_OPTLEN                      1069
#define IDB_GETSOCKOPT                  1070
#define IDB_SETSOCKOPT                  1071
#define IDC_LINGERFLAG                  1072
#define IDC_LINGERSECS                  1073
#define IDC_COMBO1                      1083
#define IDC_DESTADDR                    1084
#define IDM_ABOUT                       4105
#define IDM_CONNECT                     4300
#define IDM_CLOSE                       4305
#define IDM_OPTIONS                     4306
#define IDM_BROADCAST                   4306
#define IDD_ABOUT			4307
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        121
#define _APS_NEXT_COMMAND_VALUE         136
#define _APS_NEXT_CONTROL_VALUE         1085
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
