//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MULTITST.RC
//
#define IDI_MULTITST                    101
#define IDM_NEWSOCKET                   103
#define IDM_SENDTO                      104
#define IDM_BIND                        106
#define IDM_SOCKOPTS                    107
#define IDM_PING                        108
#define IDM_ABOUT                       109
#define IDM_DLLINFO                     110
#define IDM_EXIT                        111
#define MULTITST                        120
#define IDC_TTLVALUE                    1009
#define IDC_DESTADDR                    1015
#define IDC_SENDTO                      1017
#define IDC_DATAOUT                     1018
#define IDT_SOCKIN                      1029
#define IDT_OPTNAME                     1031
#define IDT_FPORT                       1033
#define IDC_CONNECT                     1036
#define IDC_SEND                        1039
#define IDC_SRCADDR                     1040
#define IDC_SRCPORT                     1041
#define IDC_BIND                        1042
#define IDC_BSD_OPTNAMES                1044
#define IDQUIT                          1045
#define IDC_TTLENABLE                   1046
#define IDC_DEST                        1047
#define IDC_DATALEN                     1048
#define IDC_ICMPID                      1049
#define IDC_OPEN                        1050
#define IDC_COMPILEDATE                 1050
#define IDC_ICMPSEQ                     1053
#define IDS_DLLVER                      1055
#define IDS_DLLHIVER                    1056
#define IDS_MAXSOCKS                    1059
#define IDS_MAXUDP                      1060
#define IDS_DESCRIP                     1065
#define IDS_STATUS                      1066
#define IDC_SOCKET                      1067
#define IDR_ADD                         1082
#define IDR_DROP                        1083
#define IDR_LOOP                        1084
#define IDR_TTL                         1085
#define IDC_IF                          1086
#define IDR_OTHER                       1087
#define IDT_LEVELIN                     1088
#define IDT_OPTVAL                      1089
#define IDT_OPTLEN                      1090
#define IDB_SETSOCKOPT                  1091
#define IDB_GETSOCKOPT                  1092
#define IDT_MULTIADDR                   1093
#define IDT_MULTIINTR                   1094
#define IDD_ABOUT                       1095
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        116
#define _APS_NEXT_COMMAND_VALUE         113
#define _APS_NEXT_CONTROL_VALUE         1069
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
