//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by WAL.RC
//
#define CHARGEN_SEQ                     19
#define IDD_ABOUT                       102
#define IDD_WSAPPPARMS                  103
#define IDD_APPOPTIONDLG                105
#define IDD_ABOUTBOX                    106
#define IDD_APPPARMDLG                  107
#define IDM_NEWAPP                      109
#define IDM_OOBOPTIONS                  110
#define IDM_SOCKOPTIONS                 111
#define IDM_APPOPTIONS                  112
#define IDM_CLOSELOG                    114
#define IDM_OPENSOCK                    116
#define IDM_CLOSESOCK                   117
#define IDM_ABORTSOCK                   118
#define IDC_DATASTREAM                  1001
#define IDC_DATAGRAM                    1002
#define IDC_CLIENTAPP                   1003
#define IDC_SERVERAPP                   1004
#define IDC_PORTNUMBER                  1005
#define IDM_EXIT                        1006
#define IDC_HOSTID                      1006
#define IDC_BLOCKING                    1007
#define IDC_NONBLOCKING                 1008
#define IDC_ASYNCH                      1009
#define IDC_THREADED                    1010
#define IDC_ASYNCHLOOP                  1011
#define IDC_OPMODES                     1013
#define IDC_ROLE                        1014
#define IDC_PROTOCOL                    1015
#define IDC_SERVICENAME                 1016
#define IDOPTIONS                       1018
#define IDC_READ                        1019
#define IDC_WRITE                       1020
#define IDC_BYTES_PER_IO                1024
#define IDC_IO_PER_LOOP                 1025
#define IDC_LOOP_INTERVAL               1026
#define IDC_SOUND                       1027
#define IDC_OOBSENDINTRVL               1031
#define IDC_OOBSENDAMNT                 1032
#define IDC_OOBRECVAMNT                 1033
#define IDC_OOBSEND                     1039
#define IDC_OOBPOLL                     1040
#define IDC_OOBOUTSOUND                 1042
#define IDC_OOBINSOUND                  1044
#define IDC_STATIC2                     1045
#define IDC_STATIC3                     1046
#define IDC_STATIC1                     1047
#define IDC_COMPILEDATE                 1050
#define IDC_ACCEPTCON                   1051
#define IDC_ACCEPTCONN                  1051
#define IDC_BROADCAST                   1053
#define IDC_DEBUG                       1054
#define IDC_DONTLINGER                  1055
#define IDC_DONTROUTE                   1056
#define IDC_ERROR                       1057
#define IDC_KEEPALIVE                   1058
#define IDC_LINGER                      1059
#define IDC_OOBINLINE                   1060
#define IDC_RCVBUF                      1061
#define IDC_REUSEADDR                   1062
#define IDC_SNDBUF                      1063
#define IDC_TYPE                        1064
#define IDC_TCPNODELAY                  1065
#define IDC_SOCKIN                      1066
#define IDC_LEVELIN                     1067
#define IDC_OPTVAL                      1068
#define IDC_OPTLEN                      1069
//#define IDB_GETSOCKOPT                  1070
//#define IDB_SETSOCKOPT                  1071
#define IDC_LINGERFLAG                  1072
#define IDC_LINGERSECS                  1073
#define IDC_SOCKDG                      1074
#define IDC_SOCKDS                      1075
#define IDC_MAXBYTES                    1076
#define IDB_IOADVANCED                  1078
#define IDC_LOOPUP                      1079
#define IDC_LOOPDN                      1080
#define IDC_MAX_IO_PER_LOOP             1081
#define IDR_ADD							1082
#define IDR_DROP						1083
#define IDR_LOOP						1084
#define IDR_TTL							1085
#define IDT_SOCKIN						1086
#define IDT_LEVELIN						1087
#define IDT_OPTVAL						1088
#define IDT_OPTLEN						1089
#define IDB_SETSOCKOPT					1090
#define IDB_GETSOCKOPT					1091
#define IDT_MULTIADDR					1092
#define IDT_MULTIINTR					1093
#define IDM_TILE                        4001
#define IDM_CASCADE                     4002
#define IDM_CLOSEALL                    4003
#define IDM_ARRANGE                     4004
#define IDM_NEWLOG                      4101
#define IDM_SHOWSTATS                   4102
#define IDM_RESETSTATS                  4103
#define IDM_DETAILSTATS                 4104
#define IDM_ABOUT                       4105
#define IDM_CHILD                       4200
#define IDM_FIRSTCHILD                  4201
#define IDM_CONNECT                     4300
#define IDM_WRITE_READ                  4301
#define IDM_READ_WRITE                  4302
#define IDM_WRITE                       4303
#define IDM_READ                        4304
#define IDM_CLOSE                       4305
#define IDM_OPTIONS                     4306
#define IDM_IOOPTIONS                   4306
#define IDM_ASYNC                       4307
#define CTL3D_3DCHECK                   26567
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        117
#define _APS_NEXT_COMMAND_VALUE         120
#define _APS_NEXT_CONTROL_VALUE         1083
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
